version:                "3"
services:
  this_node:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./app:/home/node/app
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      ports:
        - 8081:8081
        - 8080:8080
        - 3000:3000
      container_name:   this_node
